language: ruby

rvm:
 - 2.3.1

git:
  submodules: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git pandoc texlive-full
  - |
    git config --global user.email "dgiimblog@gmail.com"
    git config --global user.name "dgiimbot"
    git clone -b pdf https://${GITHUB_TOKEN}@github.com/fdavidcl/apuntesDGIIM.git .out

install:
  - # chmod +x .travis/texlive-install.sh
  - # .travis/texlive-install.sh
  - # export PATH="$PATH:$HOME/texlive/bin/x86_64-linux"
  - # tlmgr install wrapfig

script:
  - |
    cd Análisis\ Matemático\ I
    make
    cd ..

after_script:
  - |
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && (
    cd .out/
    git ls-files --deleted -z | xargs -0 git rm
    git add *
    git add . --all
    git commit -m "Compiled PDFs at `date`"
    git push origin pdf --quiet
    )

branches:
  only:
    - master
