language: ruby

rvm:
 - 2.3.1
 
git:
  submodules: false
  
gems:
  - pygmentize

cache:
  apt: true
#before_install:
  #- sudo add-apt-repository -y ppa:texlive-backports/ppa
addons:
  apt:
    packages:
      -pandoc
      -texlive
      -texlive-base
      -texlive-latex-extra
      -python-pygments
      -texlive-fonts-recommended
before_install:
    git config --global user.email "dgiimblog@gmail.com"
    git config --global user.name "dgiimbot"
    git clone -b pdf https://${GITHUB_TOKEN}@github.com/libreim/apuntesDGIIM.git .out

script: rake

after_success:
  - |
    [ "${TRAVIS_PULL_REQUEST}" = "false" ] && (
    cd .out/
    git ls-files --deleted -z | xargs -0 git rm
    git add *
    git add . --all
    git commit -m "Compiled PDFs at `date`"
    git push origin pdf --quiet
    )

branches:
  only:
    - master
